= Conclusion

I hope that this brief handbook has provided you with a good overview of how LiteDB stacks against SQLite and what features it makes available to you as a .NET developer.

My primary goal was to help you decide which database is the right fit for your next project.

To accomplish that, we looked at their features and how we would implement various queries to get data in and out of the databases using SQL and LINQ.

We have seen that for many CRUD scenarios, you can achieve the same result using very similar, if not identical, techniques.

SQLite retains its primacy in scenarios where the application takes advantage of its full potential.
After all, it has a 20-year head start!

The comparison was affected by my choice of a C# SQLite library, which was SQLite-net.
The SQLite side of the comparison would look different if I chose a different "`driver.`"

This concern goes away for the right side, however, since you don't need any extra library to talk to LiteDB.

This is a big plus.
Choosing LiteDB over SQLite means no longer having to worry about interop.
You know that wherever your .NET code runs, LiteDB will run as well.

Not only is LiteDB native to .NET, but it's also friendly to the contemporary programming paradigm.

JSON is everywhere.
REST APIs rule supreme.
Apps that participate in this ecosystem create, consume, and modify documents that can at any time become a JSON string and be on their way to the next API.

In this world, storing them in a document database is often the right design choice.

LiteDB also fulfills many of the core use cases that SQLite does:

* It can be your application file format.
* It can serve as a staging area for processing unreliable, "`dirty`" data that needs some clean-up and transformation before it can be handed over to the business people.
* It can be a backup target and be sent around, e-mailed, put to blob storage, and then consumed at the destination with zero additional dependencies.
It's just a file!

Whether it will be around for another 10-20 years like SQLite is to be seen, however.
The Lindy effect is at play here.
The likelihood of SQLite being here in 2050 is higher simply because it's already been here for so long.

As of now, in 2022, LiteDB is being actively developed, and there are no signs that the project should be abandoned.
I hope the project eventually gets some institutional support to guarantee its future development and support.
That way, more developers could rely on it for applications with a long time span.

In the meantime, make sure to give LiteDB a try!

Hopefully, this handbook has given you the idea of where to start and how to set up.
If there is anything unclear, I'm happy to answer any questions regarding this handbook and will incorporate your feedback in any updates I might make to it.

Thank you for reading!
You can reach me at http://tomaskohl.com[tomaskohl.com] and connect with me on https://twitter.com/tomaskohl[Twitter].
